name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    runs-on: [self-hosted, EKS-Runner-cicd]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kamblesuraj432/golangproject
    - name: Docker login
      run: docker login
    - name: Docker image push to dockerhub
      run: docker push kamblesuraj432/golangproject
